// <auto-generated />
using LuxfordPTAWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace LuxfordPTAWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260512163600_AddEventFlyerUrls")]
    partial class AddEventFlyerUrls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
